name: audio-lessons-generator-python
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - boto3=1.18.21
  - botocore=1.21.41
  - brotlipy=0.7.0
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.14.6
  - charset-normalizer=2.0.4
  - conda=4.10.3
  - conda-package-handling=1.7.3
  - cryptography=35.0.0
  - idna=3.2
  - jmespath=0.10.0
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.3
  - openssl=1.1.1l
  - pip=21.2.4
  - pycosat=0.6.3
  - pycparser=2.20
  - pydub=0.25.1
  - pyopenssl=21.0.0
  - pysocks=1.7.1
  - python=3.9.4
  - python-dateutil=2.8.2
  - python_abi=3.9
  - readline=8.1
  - requests=2.26.0
  - ruamel_yaml=0.15.100
  - s3transfer=0.5.0
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - tqdm=4.62.3
  - tzdata=2021e
  - urllib3=1.26.7
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - pip:
    - boto3-type-annotations-with-docs==0.3.1
    - dataclasses-json==0.5.6
    - marshmallow==3.14.0
    - marshmallow-enum==1.5.1
    - mypy-extensions==0.4.3
    - stringcase==1.2.0
    - typing-extensions==3.10.0.2
    - typing-inspect==0.7.1
