name: audio-lessons
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - botocore=1.27.10
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - certifi=2022.6.15
  - cffi=1.15.0
  - colorama=0.4.4
  - conda=4.13.0
  - conda-package-handling=1.8.1
  - idna=3.3
  - jmespath=1.0.0
  - ld_impl_linux-64=2.36.1
  - libffi=3.3
  - libgcc-ng=12.1.0
  - libgomp=12.1.0
  - libstdcxx-ng=12.1.0
  - libuuid=1.0.3
  - libzlib=1.2.12
  - ncurses=6.3
  - openssl=1.1.1o
  - pip=22.1.2
  - pycosat=0.6.3
  - pycparser=2.21
  - pydub=0.25.1
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python_abi=3.10
  - readline=8.1.2
  - ruamel_yaml=0.15.80
  - s3transfer=0.6.0
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - tqdm=4.64.0
  - tzdata=2022a
  - urllib3=1.26.9
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.12
  - pip:
    - boto3==1.24.10
    - boto3-type-annotations-with-docs==0.3.1
    - charset-normalizer==2.0.12
    - cryptography==37.0.2
    - dataclasses-json==0.5.7
    - marshmallow==3.16.0
    - marshmallow-enum==1.5.1
    - mypy-extensions==0.4.3
    - packaging==21.3
    - pip-review==1.1.1
    - pyparsing==3.0.9
    - requests==2.28.0
    - setuptools==62.4.0
    - stringcase==1.2.0
    - typing-extensions==4.2.0
    - typing-inspect==0.7.1
