name: audio-lessons
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - botocore=1.27.28
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - cairo=1.16.0
  - cairocffi=1.3.0
  - cairosvg=2.5.2
  - certifi=2022.6.15
  - cffi=1.15.0
  - colorama=0.4.5
  - conda-package-handling=1.8.1
  - cssselect2=0.2.1
  - defusedxml=0.7.1
  - fontconfig=2.13.1
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - jmespath=0.10.0
  - jpeg=9e
  - jsonpickle=2.2.0
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - libffi=3.3
  - libgcc-ng=12.1.0
  - libgomp=12.1.0
  - libpng=1.6.37
  - libstdcxx-ng=12.1.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.14
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - ncurses=6.3
  - openssl=1.1.1q
  - pcre=8.45
  - pip=22.1.2
  - pixman=0.40.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pydub=0.25.1
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python_abi=3.10
  - readline=8.1.2
  - ruamel_yaml=0.15.80
  - s3transfer=0.6.0
  - simplejson=3.17.6
  - six=1.16.0
  - sqlite=3.38.5
  - tinycss2=1.1.1
  - tk=8.6.12
  - tqdm=4.64.0
  - tzdata=2022a
  - urllib3=1.26.9
  - webencodings=0.5.1
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - boto3==1.24.10
    - boto3-type-annotations-with-docs==0.3.1
    - charset-normalizer==2.0.12
    - cryptography==37.0.2
    - dataclasses-json==0.5.7
    - lxml==4.9.1
    - marshmallow==3.16.0
    - marshmallow-enum==1.5.1
    - mypy-extensions==0.4.3
    - packaging==21.3
    - pillow==9.1.1
    - pip-review==1.1.1
    - pyparsing==3.0.9
    - qrcode==7.3.1
    - requests==2.28.0
    - setuptools==62.4.0
    - stringcase==1.2.0
    - svglue==0.3.0
    - typing-extensions==4.2.0
    - typing-inspect==0.7.1
